### ISSUE TITLE
Converting the fifo file

### ISSUE THREAD

**Issue by garaw7** [adrz/twitch-realtime-handler#1]
Hey I'm building a speech recognition and was doing this on my own with ffmpeg and had a hard time trying to load the audio file into the model. I was able to use urlopen() and put the url then convert with pydub to a wav then feed it into my model. I ran into your github and was wondering how i can pass this into my model since is a fifo. How would i convert that to a .wav so i can load it with pytorch or librosa?

**Comment by adrz** [comment]
Hi @warsameF ,

I hope I understand correctly your issue. There is an example https://github.com/adrz/twitch-realtime-handler/blob/master/examples/realtime-transcript.py that I think do what you want:
```python
audio_grabber = TwitchAudioGrabber(
                                   twitch_url=twitch_url,
                                   dtype=np.int16,
                                   segment_length=2,
                                   channels=1,
                                   rate=16000)
while True:
    audio_segment = audio_grabber.grab_raw()
```
will continuously generate segment of 2 seconds as a numpy array format. you could send convert it into a tensor to feed your torch model. Alternatively if you want tu use pydub you could simply:

```python
raw_wav = AudioSegment.from_raw(
                    raw, sample_width=2, frame_rate=16000, channels=1)
```

is it what you want to do ?

**Comment by warsameF** [comment]
Hey @adrz thanks for responding, I tried the pydub method wjtb torchaudio.load() and librosa.load() but is not working because the file types aren't the same. How can i load it into those functions they need a file like object. I used this method earlier before I found your github
```
wav = io.BytesIO()
with urlopen(streamURL) as r:
 	    r.seek = lambda *args: None  # allow pydub to call seek(0)
	    pydub.AudioSegment.from_file(r).export(wav, "wav")
wav.seek(0)
```
Then i would pass the wav file into torchaudio.load() or librosa.load() while i call wav.seek(0) to reset the wav and this works but is really inconsistent because I'm guessing the file is to large and wav2vec2 parsing with small audio segments. This method doesn't actually make a file so i preferred this because i thought it would be able to process faster. Your method would work better because I could generate segments to pass into wav2vec but it doesn't work when i try this:
```
if audio_segment:
		raw = BytesIO(audio_segment)
		raw_wav = pydub.AudioSegment.from_raw(raw, sample_width=2, frame_rate=16000, channels=1)
		data=BytesIO()
		raw_wav.export(data,format="wav")
		h=get_transcription(data.read())
		print(h)
```
I get a system error stemming from , speech, sr = librosa.load(audio_file, sr=16000), so what am I doing wrong is there something I'm forgetting. Also is there a way to do it without saving to a file, you mentioned converting the numpy array to a tensor. How would I do that so torchaudio.load() would accept it? If you could help me it would be appreciated, thank you for your time.

**Comment by warsameF** [comment]
@adrz  Thank you got it to work idk wat i did but it started working now. This got it to work:
```python
	if audio_segment:
		raw = BytesIO(audio_segment)
		raw_wav = pydub.AudioSegment.from_raw(raw, sample_width=2, frame_rate=16000, channels=1)
		file=BytesIO()
		raw_wav.export(file, format="wav")
		h=get_transcription(file)
		print(h)
```
Also last thing is there anyway to optimise it so it runs faster. Is there a faster way to get it to a file so i can pass it to get_transcript(). If you have time, I would really appreciate the help.

**Comment by garaw7** [comment]
thank you i fixed it, nvm the best thing i learned today is that you can use this with pytorch and use the wav2vec2 models to pass the file into torchaudio.load() or librosa.load(). It works but it isn't that accurate. I didn't compute the error rate.
